import { useState, useEffect } from "react"
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from "../components/ui/card"
import { Button } from "../components/ui/button"
import { Badge } from "../components/ui/badge"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "../components/ui/table"
import { FileDown, Trash2 } from "lucide-react"
import { fetchGeneratedRequests, deleteGeneratedRequest } from "../store/data"

interface GeneratedRequest {
  id: string
  request_number: string
  generated_by: string
  generated_at: string
  file_path: string
  status: string
  item_count: number
}

export function GeneratedRequests() {
  const [requests, setRequests] = useState<GeneratedRequest[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    loadRequests()
  }, [])

  const loadRequests = async () => {
    setLoading(true)
    const data = await fetchGeneratedRequests()
    setRequests(data)
    setLoading(false)
  }

  const handleDelete = async (id: string) => {
    if (!confirm("Delete this request?")) return
    await deleteGeneratedRequest(id)
    loadRequests()
  }

  const handleDownload = (req: GeneratedRequest) => {
    alert(`Downloading ${req.request_number}`)
  }

  const getStatusVariant = (status: string) => {
    switch (status) {
      case "Completed":
        return "active"
      case "Pending":
        return "expiring"
      case "Sent":
        return "default"
      default:
        return "default"
    }
  }

  if (loading) {
    return <div className="p-4">Loading...</div>
  }

  return (
    <div className="space-y-6 flex flex-col h-full">
      <div>
        <h2 className="text-2xl font-bold tracking-tight">
          Generated Requests
        </h2>
        <p className="text-muted-foreground">
          View and download previously generated price request forms.
        </p>
      </div>

      <Card className="flex-1 flex flex-col overflow-hidden">
        <CardHeader>
          <CardTitle>Request History</CardTitle>
          <CardDescription>
            All generated Excel request forms are listed below.
          </CardDescription>
        </CardHeader>
        <CardContent className="flex-1 overflow-auto p-0">
          <Table>
            <TableHeader className="sticky top-0 bg-muted/90 backdrop-blur z-10">
              <TableRow>
                <TableHead>File Name</TableHead>
                <TableHead>Generated At</TableHead>
                <TableHead>Generated By</TableHead>
                <TableHead className="text-right">Items</TableHead>
                <TableHead>Status</TableHead>
                <TableHead className="text-right w-32">Action</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {requests.length > 0 ? (
                requests.map((req) => (
                  <TableRow key={req.id}>
                    <TableCell className="font-medium">
                      {req.request_number}
                    </TableCell>
                    <TableCell className="text-muted-foreground text-xs">
                      {new Date(req.generated_at).toLocaleString()}
                    </TableCell>
                    <TableCell>{req.generated_by || "System"}</TableCell>
                    <TableCell className="text-right">
                      {req.item_count}
                    </TableCell>
                    <TableCell>
                      <Badge variant={getStatusVariant(req.status)}>
                        {req.status}
                      </Badge>
                    </TableCell>
                    <TableCell className="text-right">
                      <div className="flex gap-2 justify-end">
                        <Button size="sm" variant="outline" onClick={() => handleDownload(req)}>
                          <FileDown className="h-4 w-4 mr-1" />
                          Download
                        </Button>
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => handleDelete(req.id)}
                        >
                          <Trash2 className="h-4 w-4 text-red-500" />
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))
              ) : (
                <TableRow>
                  <TableCell colSpan={6} className="h-24 text-center">
                    No generated requests yet.
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  )
}
