import { useState } from "react"
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from "../components/ui/card"
import { Button } from "../components/ui/button"
import { Badge } from "../components/ui/badge"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "../components/ui/table"
import { FileDown, Trash2 } from "lucide-react"

interface GeneratedRequest {
  id: string
  fileName: string
  generatedAt: string
  generatedBy: string
  itemCount: number
  status: "Pending" | "Sent" | "Completed"
}

const initialRequests: GeneratedRequest[] = [
  {
    id: "1",
    fileName: "Request-2024-001.xlsx",
    generatedAt: "2024-06-15T10:30:00Z",
    generatedBy: "Admin",
    itemCount: 12,
    status: "Completed",
  },
  {
    id: "2",
    fileName: "Request-2024-002.xlsx",
    generatedAt: "2024-06-20T14:00:00Z",
    generatedBy: "Admin",
    itemCount: 8,
    status: "Pending",
  },
]

export function GeneratedRequests() {
  const [requests, setRequests] = useState<GeneratedRequest[]>(initialRequests)

  const handleDelete = (id: string) => {
    setRequests(requests.filter((r) => r.id !== id))
  }

  const getStatusVariant = (status: string) => {
    switch (status) {
      case "Completed":
        return "active"
      case "Pending":
        return "expiring"
      case "Sent":
        return "default"
      default:
        return "default"
    }
  }

  return (
    <div className="space-y-6 flex flex-col h-full">
      <div>
        <h2 className="text-2xl font-bold tracking-tight">
          Generated Requests
        </h2>
        <p className="text-muted-foreground">
          View and download previously generated price request forms.
        </p>
      </div>

      <Card className="flex-1 flex flex-col overflow-hidden">
        <CardHeader>
          <CardTitle>Request History</CardTitle>
          <CardDescription>
            All generated Excel request forms are listed below.
          </CardDescription>
        </CardHeader>
        <CardContent className="flex-1 overflow-auto p-0">
          <Table>
            <TableHeader className="sticky top-0 bg-muted/90 backdrop-blur z-10">
              <TableRow>
                <TableHead>File Name</TableHead>
                <TableHead>Generated At</TableHead>
                <TableHead>Generated By</TableHead>
                <TableHead className="text-right">Items</TableHead>
                <TableHead>Status</TableHead>
                <TableHead className="text-right w-32">Action</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {requests.length > 0 ? (
                requests.map((req) => (
                  <TableRow key={req.id}>
                    <TableCell className="font-medium">
                      {req.fileName}
                    </TableCell>
                    <TableCell className="text-muted-foreground text-xs">
                      {new Date(req.generatedAt).toLocaleString()}
                    </TableCell>
                    <TableCell>{req.generatedBy}</TableCell>
                    <TableCell className="text-right">
                      {req.itemCount}
                    </TableCell>
                    <TableCell>
                      <Badge variant={getStatusVariant(req.status)}>
                        {req.status}
                      </Badge>
                    </TableCell>
                    <TableCell className="text-right">
                      <div className="flex gap-2 justify-end">
                        <Button size="sm" variant="outline">
                          <FileDown className="h-4 w-4 mr-1" />
                          Download
                        </Button>
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => handleDelete(req.id)}
                        >
                          <Trash2 className="h-4 w-4 text-red-500" />
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))
              ) : (
                <TableRow>
                  <TableCell colSpan={6} className="h-24 text-center">
                    No generated requests yet.
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  )
}
